export * from "./about";
export * from "./contact";
export * from "./customers-page";
export * from "./error-page";
export * from "./forgot-password-page";
export * from "./home";
export * from "./login-page";
export * from "./not-found";
export * from "./reset-password-page";
