/**
 * Type-safe Route Helpers (Auto-generated)
 *
 * This file is automatically generated from your app directory structure.
 * DO NOT EDIT MANUALLY - Run 'npm run generate:routes' to regenerate.
 *
 * Usage:
 * ```ts
 * import { getPath } from '@/features/navigation';
 *
 * // Simple route
 * getPath.home() // => '/'
 * getPath.login() // => '/login'
 *
 * // With dynamic params
 * getPath.resetPassword({ token: 'abc123' }) // => '/reset-password/abc123'
 *
 * // With query strings (use 'qs' key)
 * getPath.home({ qs: { redirect: '/dashboard' } }) // => '/?redirect=/dashboard'
 * getPath.resetPassword({ token: 'abc', qs: { returnUrl: '/profile' } })
 * // => '/reset-password/abc?returnUrl=/profile'
 * ```
 */

type QueryParams = Record<string, string | number | boolean | undefined>;
type WithQueryString<T = never> = T extends never
  ? { qs?: QueryParams }
  : T & { qs?: QueryParams };

/**
 * Build query string from params object
 */
function buildQueryString(params: QueryParams): string {
  const filtered = Object.entries(params).filter(
    ([, value]) => value !== undefined && value !== null
  );

  if (filtered.length === 0) return "";

  const searchParams = new URLSearchParams();
  filtered.forEach(([key, value]) => {
    searchParams.append(key, String(value));
  });

  return `?${searchParams.toString()}`;
}

/**
 * Route builder helper
 */
function createRoute<TParams extends Record<string, string> = never>(
  path: string,
  paramKeys: string[] = []
) {
  return (
    params?: WithQueryString<TParams>
  ): string => {
    if (!params) return path;

    let finalPath = path;
    const queryParams: QueryParams = {};

    // Extract query string params
    if ('qs' in params && params.qs) {
      Object.assign(queryParams, params.qs);
    }

    // Replace path params
    paramKeys.forEach((key) => {
      if (key in params && params[key as keyof typeof params] !== undefined) {
        finalPath = finalPath.replace(`[${key}]`, String(params[key as keyof typeof params]));
      }
    });

    // Copy remaining params to query string (except 'qs')
    Object.entries(params).forEach(([key, value]) => {
      if (key !== 'qs' && !paramKeys.includes(key) && value !== undefined) {
        queryParams[key] = value as string | number | boolean;
      }
    });

    // Add query string
    const queryString = buildQueryString(queryParams);
    return `${finalPath}${queryString}`;
  };
}

/**
 * Application Routes
 * Auto-generated based on app directory structure
 */
export const getPath = {
  // Main routes
  home: createRoute("/"),

  // Debug-notifications routes
  debugNotifications: createRoute("/debug-notifications"),

  // Forgot-password routes
  forgotPassword: createRoute("/forgot-password"),

  // Login routes
  login: createRoute("/login"),

  // Reset-password routes
  resetPassword: createRoute<{ token: string }>("/reset-password/[token]", ["token"]),
} as const;

/**
 * Route type inference
 */
export type Routes = typeof getPath;
export type RouteName = keyof Routes;
